
import gerasom.Musica;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lorenzo
 */
public class TelaInicial extends javax.swing.JFrame {

    private JFileChooser openFileChooser;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();

        openFileChooser = new JFileChooser();
        openFileChooser.setFileFilter(new FileNameExtensionFilter("Only Text Files", "txt"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HelpButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Owners = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        PlayButton = new javax.swing.JButton();
        generateFileButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BPMSelector = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fileNameField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        HelpButton.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        HelpButton.setText("Help");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gerasom");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        Title.setFont(new java.awt.Font("Monospaced", 2, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(102, 51, 255));
        Title.setText("gerasom");
        jPanel1.add(Title);
        Title.setBounds(90, 70, 210, 50);

        Owners.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        Owners.setForeground(new java.awt.Color(255, 255, 255));
        Owners.setText(" © Astélio José W., Leonardo H., Lorenzo C.");
        jPanel1.add(Owners);
        Owners.setBounds(20, 510, 310, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 350, 540);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchButton.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        SearchButton.setText("Search File");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 150, -1));

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setText("Type the text you want to transform in sound...");
        jScrollPane1.setViewportView(textArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 110));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Save File:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        PlayButton.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        PlayButton.setText("Play");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel2.add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, -1));

        generateFileButton.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        generateFileButton.setText("Generate File");
        generateFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateFileButtonActionPerformed(evt);
            }
        });
        jPanel2.add(generateFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 140, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 550, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 194, 550, -1));

        BPMSelector.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        BPMSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grave", "Largo", "Larghetto", "Lento", "Adagio", "Adagietto", "Andante", "Andantino", "Moderato", "Allegretto", "Allegro", "Vivace", "Pretissimo" }));
        BPMSelector.setToolTipText("");
        BPMSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPMSelectorActionPerformed(evt);
            }
        });
        jPanel2.add(BPMSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setText("Search File or Type Text:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setText("Play Music:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        fileNameField.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        fileNameField.setText("Type the file name...");
        fileNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(fileNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 260, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 550, 10));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setText("Select BPM:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        helpButton.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 200, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 550, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 450, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        int returnValue = openFileChooser.showOpenDialog(this);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = openFileChooser.getSelectedFile();
            BufferedReader in;
            String content = null;

            try {
                in = new BufferedReader(new FileReader(selectedFile));
                content = in.readLine();
            } catch (FileNotFoundException ex) {
                content = "Erro na Leitura";
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }

            textArea.setText(content);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        // TODO add your handling code here:
        Musica music = new Musica();
        music.setEntradaUsuario(textArea.getText());
        music.setTempoBPM((String) BPMSelector.getSelectedItem());

        Musica.playMusic(music.getEntradaUsuario(), music.getTempoBPM());
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void generateFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateFileButtonActionPerformed
        // TODO add your handling code here:
        Musica music = new Musica();
        music.setEntradaUsuario(textArea.getText());
        music.setTempoBPM((String) BPMSelector.getSelectedItem());

        try {
            Musica.createMidiFile(music.getEntradaUsuario(), music.getTempoBPM(), fileNameField.getText());
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_generateFileButtonActionPerformed

    private void BPMSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPMSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPMSelectorActionPerformed

    private void fileNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameFieldActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        TelaHelp dialog = new TelaHelp(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BPMSelector;
    private javax.swing.JLabel Background;
    private javax.swing.JButton HelpButton;
    private javax.swing.JLabel Owners;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JButton generateFileButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
